when:
  - event: push
    branch: main

steps:
  restore-cache:
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  install:
    image: node
    commands:
      - yarn

  build-site:
    image: node
    commands:
      - yarn build

  rebuild-cache:
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  build-image:
    image: woodpeckerci/plugin-docker-buildx
    commands:
      - docker builder prune -f # don't add -a here, it will destroy build cache
      - docker container prune -f
      - docker compose -f docker-compose.yml up -d --build --remove-orphans

  discord-notification:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
    # when:
    #   status: failure
