when:
  - event: push
    branch: main

steps:
  install:
    image: node
    commands:
      - yarn
  build-site:
    image: node
    commands:
      - yarn build
  build-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: .woodpecker/Dockerfile
      repo: localhost:5000/ilovetrees-ui
      registry: localhost:5000
      tags: latest
