when:
  - event: push
    branch: main

steps:
  restore-cache:
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  install:
    image: node
    commands:
      - yarn

  build-site:
    image: node
    commands:
      - yarn build

  rebuild-cache:
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache

  build-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: .woodpecker/Dockerfile
      repo: ilovetrees-ui
      tags: latest
      dry-run: true

  discord-notification:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
