when:
  - event: push
    branch: main

steps:
  install:
    image: node
    commands:
      - yarn
  build-site:
    image: node
    commands:
      - yarn build
  build-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: .woodpecker/Dockerfile
      repo: ilovetrees-ui
      tags: latest
      dry-run: true
  discord-notification:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN}
