when:
  - event: push
    branch: main

steps:
  install:
    image: node
    commands:
      - yarn
  build-site:
    image: node
    commands:
      - yarn build
  build-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dry-run: true
      dockerfile: .woodpecker/Dockerfile
      repo: ilovetrees-ui
      tags: latest
