name: Build Vue
on:
  push:
    branches: main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v4
      - name: Build Vue
        run: |
          yarn
          yarn build
          cd dist
          ln -s index.html 404.html
          git config --global init.defaultBranch main
          git init
          git config user.name "github-actions[bot]"
          git config user.email "1462379+fmakdemir@users.noreply.github.com"
          git add -A
          git commit -m 'gh deployment'
          git push -f https://fmakdemir:${{ secrets.GITHUB_TOKEN }}@github.com/fmakdemir/ilovetrees-ui.git main:gh-pages
        shell: bash
