name: Build Vue
on:
  push:
    branches: main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Build Vue
        run: |
          yarn
          yarn build
          cd dist
          ln -s index.html 404.html
          git init
          git add -A
          git commit -m 'gh deployment'
          git push -f https://fmakdemir:${{ secrets.GITHUB_TOKEN }}@github.com/fmakdemir/ilovetrees-ui.git master:gh-pages
        shell: bash
